export const PLATFORM_FEE_PERCENT = 30;

// Lab platform fee is negotiable per lab based on quality & market presence
// Range: 10% - 30%, set during lab approval
export const LAB_FEE_RANGE = { min: 10, max: 30 };

// Medical Store category-based platform fees
export const STORE_FEE_CATEGORIES = {
  surgical: { name: 'Surgical Items', percent: 50 },
  multinational: { name: 'Multinational / Branded', percent: 10 },
  local: { name: 'Local / Generic Medicines', percent: 20 },
  otc: { name: 'OTC & Personal Care', percent: 20 },
  devices: { name: 'Medical Devices', percent: 15 },
  supplements: { name: 'Vitamins & Supplements', percent: 20 },
};

export const PAYMENT_METHODS = [
  {
    id: 'cash',
    name: 'Cash on Service',
    icon: 'money-bill-wave',
    description: 'Pay in cash when the provider arrives',
    color: '#10B981',
    bgColor: '#DCFCE7',
  },
  {
    id: 'card',
    name: 'Credit / Debit Card',
    icon: 'credit-card',
    description: 'Visa, Mastercard, or any debit card',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
  },
  {
    id: 'online',
    name: 'Online Transfer',
    icon: 'university',
    description: 'Bank transfer or mobile wallet (JazzCash, Easypaisa)',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
  },
];

export function calculateFees(servicePrice) {
  const platformFee = Math.round(servicePrice * (PLATFORM_FEE_PERCENT / 100));
  const providerEarnings = servicePrice - platformFee;
  return {
    servicePrice,
    platformFee,
    providerEarnings,
    totalPatientPays: servicePrice,
  };
}

export const PROVIDER_TRANSACTIONS = [
  {
    id: 't1',
    patientName: 'Ali Hassan',
    serviceName: 'Home Doctor Visit',
    date: '2026-05-04',
    servicePrice: 500,
    platformFee: 150,
    providerEarnings: 350,
    paymentMethod: 'cash',
    status: 'paid',
  },
  {
    id: 't2',
    patientName: 'Fatima Noor',
    serviceName: 'Home Doctor Visit',
    date: '2026-05-03',
    servicePrice: 500,
    platformFee: 150,
    providerEarnings: 350,
    paymentMethod: 'online',
    status: 'paid',
  },
  {
    id: 't3',
    patientName: 'Usman Tariq',
    serviceName: 'Home Doctor Visit',
    date: '2026-05-02',
    servicePrice: 500,
    platformFee: 150,
    providerEarnings: 350,
    paymentMethod: 'card',
    status: 'paid',
  },
  {
    id: 't4',
    patientName: 'Sara Khan',
    serviceName: 'Home Doctor Visit',
    date: '2026-05-01',
    servicePrice: 500,
    platformFee: 150,
    providerEarnings: 350,
    paymentMethod: 'cash',
    status: 'pending',
  },
  {
    id: 't5',
    patientName: 'Kamran Ahmed',
    serviceName: 'Home Doctor Visit',
    date: '2026-04-30',
    servicePrice: 500,
    platformFee: 150,
    providerEarnings: 350,
    paymentMethod: 'online',
    status: 'paid',
  },
];

// Example lab with 15% negotiated fee (based on quality & market presence)
export const CURRENT_LAB_FEE_PERCENT = 15;

export const LAB_TRANSACTIONS = [
  {
    id: 'lt1',
    patientName: 'Ali Hassan',
    testName: 'Complete Blood Count (CBC)',
    date: '2026-05-04',
    servicePrice: 500,
    feePercent: 15,
    platformFee: 75,
    labEarnings: 425,
    paymentMethod: 'cash',
    status: 'paid',
  },
  {
    id: 'lt2',
    patientName: 'Fatima Noor',
    testName: 'Thyroid Function Test',
    date: '2026-05-03',
    servicePrice: 1200,
    feePercent: 15,
    platformFee: 180,
    labEarnings: 1020,
    paymentMethod: 'online',
    status: 'paid',
  },
  {
    id: 'lt3',
    patientName: 'Usman Tariq',
    testName: 'Liver Function Test',
    date: '2026-05-02',
    servicePrice: 800,
    feePercent: 15,
    platformFee: 120,
    labEarnings: 680,
    paymentMethod: 'card',
    status: 'paid',
  },
  {
    id: 'lt4',
    patientName: 'Nadia Raza',
    testName: 'Urine Analysis',
    date: '2026-05-01',
    servicePrice: 300,
    feePercent: 15,
    platformFee: 45,
    labEarnings: 255,
    paymentMethod: 'cash',
    status: 'pending',
  },
];

export const STORE_TRANSACTIONS = [
  {
    id: 'st1',
    patientName: 'Ali Hassan',
    orderName: 'Augmentin 625mg, Panadol, Brufen',
    category: 'multinational',
    categoryLabel: 'Multinational / Branded',
    date: '2026-05-04',
    servicePrice: 850,
    feePercent: 10,
    platformFee: 85,
    storeEarnings: 765,
    paymentMethod: 'cash',
    status: 'paid',
  },
  {
    id: 'st2',
    patientName: 'Sana Khan',
    orderName: 'Surgical Gloves, Syringes, Bandages',
    category: 'surgical',
    categoryLabel: 'Surgical Items',
    date: '2026-05-03',
    servicePrice: 2800,
    feePercent: 50,
    platformFee: 1400,
    storeEarnings: 1400,
    paymentMethod: 'online',
    status: 'paid',
  },
  {
    id: 'st3',
    patientName: 'Usman Tariq',
    orderName: 'BP Monitor, Digital Thermometer',
    category: 'devices',
    categoryLabel: 'Medical Devices',
    date: '2026-05-02',
    servicePrice: 3500,
    feePercent: 15,
    platformFee: 525,
    storeEarnings: 2975,
    paymentMethod: 'card',
    status: 'paid',
  },
  {
    id: 'st4',
    patientName: 'Fatima Noor',
    orderName: 'Vitamin D3, Calcium, Iron Supplement',
    category: 'supplements',
    categoryLabel: 'Vitamins & Supplements',
    date: '2026-05-01',
    servicePrice: 1200,
    feePercent: 20,
    platformFee: 240,
    storeEarnings: 960,
    paymentMethod: 'cash',
    status: 'pending',
  },
  {
    id: 'st5',
    patientName: 'Kamran Ahmed',
    orderName: 'Local Cough Syrup, Paracetamol Generic',
    category: 'local',
    categoryLabel: 'Local / Generic',
    date: '2026-04-30',
    servicePrice: 400,
    feePercent: 20,
    platformFee: 80,
    storeEarnings: 320,
    paymentMethod: 'cash',
    status: 'paid',
  },
];

export const SPECIALIST_FEE_PERCENT = 30;

export const SPECIALIST_CATEGORIES = {
  medical_officer: { name: 'Medical Officer', fee: 1500 },
  general_physician: { name: 'General Physician', fee: 2500 },
  cardiologist: { name: 'Cardiologist', fee: 3500 },
  neurologist: { name: 'Neurologist', fee: 4000 },
  orthopedic: { name: 'Orthopedic Surgeon', fee: 3500 },
  dermatologist: { name: 'Dermatologist', fee: 3000 },
  pediatrician: { name: 'Pediatrician', fee: 3000 },
  gynecologist: { name: 'Gynecologist', fee: 4000 },
  ent: { name: 'ENT Specialist', fee: 3000 },
  pulmonologist: { name: 'Pulmonologist', fee: 4000 },
  gastro: { name: 'Gastroenterologist', fee: 4500 },
  senior_specialist: { name: 'Senior Specialist / Professor', fee: 5000 },
};

export const SPECIALIST_TRANSACTIONS = [
  {
    id: 'spt1',
    patientName: 'Ali Hassan',
    visitType: 'General Checkup',
    category: 'medical_officer',
    categoryLabel: 'Medical Officer',
    date: '2026-05-04',
    servicePrice: 1500,
    feePercent: 30,
    platformFee: 450,
    doctorEarnings: 1050,
    paymentMethod: 'cash',
    status: 'paid',
  },
  {
    id: 'spt2',
    patientName: 'Fatima Noor',
    visitType: 'Heart Consultation',
    category: 'cardiologist',
    categoryLabel: 'Cardiologist',
    date: '2026-05-03',
    servicePrice: 3500,
    feePercent: 30,
    platformFee: 1050,
    doctorEarnings: 2450,
    paymentMethod: 'online',
    status: 'paid',
  },
  {
    id: 'spt3',
    patientName: 'Usman Tariq',
    visitType: 'Follow-up Visit',
    category: 'medical_officer',
    categoryLabel: 'Medical Officer',
    date: '2026-05-02',
    servicePrice: 1500,
    feePercent: 30,
    platformFee: 450,
    doctorEarnings: 1050,
    paymentMethod: 'card',
    status: 'paid',
  },
  {
    id: 'spt4',
    patientName: 'Nadia Raza',
    visitType: 'Skin Consultation',
    category: 'dermatologist',
    categoryLabel: 'Dermatologist',
    date: '2026-05-01',
    servicePrice: 3000,
    feePercent: 30,
    platformFee: 900,
    doctorEarnings: 2100,
    paymentMethod: 'cash',
    status: 'pending',
  },
  {
    id: 'spt5',
    patientName: 'Kamran Ahmed',
    visitType: 'Child Checkup',
    category: 'pediatrician',
    categoryLabel: 'Pediatrician',
    date: '2026-04-30',
    servicePrice: 3000,
    feePercent: 30,
    platformFee: 900,
    doctorEarnings: 2100,
    paymentMethod: 'online',
    status: 'paid',
  },
];

export const PATIENT_PAYMENT_HISTORY = [
  {
    id: 'ph1',
    serviceName: 'Home Doctor Visit',
    providerName: 'Dr. Ahmed Khan',
    date: '2026-05-04',
    amount: 500,
    paymentMethod: 'cash',
    status: 'paid',
    icon: 'stethoscope',
    color: '#0D6EFD',
  },
  {
    id: 'ph2',
    serviceName: 'IV Injection & Drip',
    providerName: 'Nurse Sarah Ali',
    date: '2026-04-28',
    amount: 300,
    paymentMethod: 'online',
    status: 'paid',
    icon: 'syringe',
    color: '#00C48C',
  },
  {
    id: 'ph3',
    serviceName: 'Lab Tests',
    providerName: 'HealthLab Services',
    date: '2026-04-25',
    amount: 200,
    paymentMethod: 'card',
    status: 'paid',
    icon: 'flask',
    color: '#F59E0B',
  },
];
