export const NEARBY_PROVIDERS = [
  {
    id: 'p1',
    name: 'Dr. Ahmed Khan',
    role: 'Doctor',
    specialization: 'General Physician',
    icon: 'stethoscope',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    rating: 4.9,
    reviewCount: 142,
    distance: '0.8 km',
    distanceValue: 0.8,
    estimatedTime: '15 min',
    price: 150,
    isAvailable: true,
    experience: '8 years',
    qualifications: 'MBBS, FCPS',
    bio: 'Experienced general physician specializing in home consultations. Available for routine checkups, chronic disease management, and urgent care.',
    reviews: [
      { name: 'Ali H.', rating: 5, comment: 'Very professional and caring doctor. Highly recommended!', date: '2 days ago' },
      { name: 'Sara K.', rating: 5, comment: 'Arrived on time and was very thorough with the examination.', date: '1 week ago' },
      { name: 'Usman T.', rating: 4, comment: 'Good consultation. Explained everything clearly.', date: '2 weeks ago' },
    ],
    latitude: 24.8607,
    longitude: 67.0011,
  },
  {
    id: 'p2',
    name: 'Nurse Fatima Ali',
    role: 'Nurse',
    specialization: 'IV Therapy & Wound Care',
    icon: 'user-nurse',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    rating: 4.8,
    reviewCount: 98,
    distance: '1.2 km',
    distanceValue: 1.2,
    estimatedTime: '20 min',
    price: 80,
    isAvailable: true,
    experience: '5 years',
    qualifications: 'BSN, RN',
    bio: 'Registered nurse with expertise in IV therapy, wound care, and post-surgical patient care at home.',
    reviews: [
      { name: 'Nadia R.', rating: 5, comment: 'Very gentle with the IV. Made the whole process comfortable.', date: '3 days ago' },
      { name: 'Imran M.', rating: 5, comment: 'Professional and caring. Will book again.', date: '5 days ago' },
    ],
    latitude: 24.8650,
    longitude: 67.0050,
  },
  {
    id: 'p3',
    name: 'Dr. Hassan Raza',
    role: 'Doctor',
    specialization: 'Pediatrician',
    icon: 'stethoscope',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    rating: 4.7,
    reviewCount: 87,
    distance: '1.5 km',
    distanceValue: 1.5,
    estimatedTime: '22 min',
    price: 180,
    isAvailable: true,
    experience: '10 years',
    qualifications: 'MBBS, DCH',
    bio: 'Pediatrician specializing in child healthcare at home. Vaccinations, growth monitoring, and childhood illness management.',
    reviews: [
      { name: 'Ayesha B.', rating: 5, comment: 'Great with kids! My son was very comfortable.', date: '1 week ago' },
    ],
    latitude: 24.8580,
    longitude: 67.0080,
  },
  {
    id: 'p4',
    name: 'Tech. Zain Malik',
    role: 'Lab Technician',
    specialization: 'Blood Tests & Diagnostics',
    icon: 'flask',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    rating: 4.9,
    reviewCount: 203,
    distance: '2.0 km',
    distanceValue: 2.0,
    estimatedTime: '25 min',
    price: 30,
    isAvailable: true,
    experience: '6 years',
    qualifications: 'BSc MLT',
    bio: 'Certified medical lab technician. Home sample collection for CBC, lipid profile, thyroid, liver, kidney function tests, and more.',
    reviews: [
      { name: 'Kamran S.', rating: 5, comment: 'Quick and painless blood draw. Reports delivered same day.', date: '2 days ago' },
      { name: 'Sana J.', rating: 5, comment: 'Very professional. Results were accurate.', date: '1 week ago' },
    ],
    latitude: 24.8620,
    longitude: 67.0120,
  },
  {
    id: 'p5',
    name: 'Tech. Bilal Ahmed',
    role: 'X-Ray Technician',
    specialization: 'Portable X-Ray',
    icon: 'x-ray',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    rating: 4.6,
    reviewCount: 56,
    distance: '3.1 km',
    distanceValue: 3.1,
    estimatedTime: '35 min',
    price: 120,
    isAvailable: false,
    experience: '4 years',
    qualifications: 'BSc Radiology',
    bio: 'Qualified radiographer with portable X-ray equipment. Chest, bone, joint, and abdominal X-rays at your home.',
    reviews: [
      { name: 'Tariq H.', rating: 4, comment: 'Good service. Digital report was clear.', date: '3 days ago' },
    ],
    latitude: 24.8560,
    longitude: 67.0150,
  },
  {
    id: 'p6',
    name: 'Physio. Amna Shah',
    role: 'Physiotherapist',
    specialization: 'Sports & Rehab',
    icon: 'running',
    color: '#14B8A6',
    bgColor: '#CCFBF1',
    rating: 4.8,
    reviewCount: 112,
    distance: '1.8 km',
    distanceValue: 1.8,
    estimatedTime: '22 min',
    price: 90,
    isAvailable: true,
    experience: '7 years',
    qualifications: 'DPT, MSPT',
    bio: 'Licensed physiotherapist offering sports injury rehab, post-surgical recovery, back pain therapy, and mobility exercises.',
    reviews: [
      { name: 'Danish W.', rating: 5, comment: 'Excellent therapy sessions. My back pain improved significantly!', date: '4 days ago' },
      { name: 'Hira N.', rating: 5, comment: 'Very knowledgeable. Great post-surgery rehab program.', date: '2 weeks ago' },
    ],
    latitude: 24.8640,
    longitude: 67.0030,
  },
  {
    id: 'p7',
    name: 'Nurse Sadia Qureshi',
    role: 'Nurse',
    specialization: 'Elderly Care',
    icon: 'user-nurse',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    rating: 4.9,
    reviewCount: 178,
    distance: '0.5 km',
    distanceValue: 0.5,
    estimatedTime: '10 min',
    price: 100,
    isAvailable: true,
    experience: '9 years',
    qualifications: 'BSN, RN, Geriatric Care Cert.',
    bio: 'Specialized in elderly patient care. Medication management, vital signs monitoring, catheter care, and daily health assistance.',
    reviews: [
      { name: 'Rashid A.', rating: 5, comment: 'Takes amazing care of my father. Like family!', date: '1 day ago' },
      { name: 'Meena P.', rating: 5, comment: 'Patient and professional. Highly recommend for elderly care.', date: '3 days ago' },
    ],
    latitude: 24.8615,
    longitude: 66.9990,
  },
  {
    id: 'p8',
    name: 'Nurse Hina Batool',
    role: 'Nurse',
    specialization: 'Wound Dressing & Catheterization',
    icon: 'band-aid',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    rating: 4.8,
    reviewCount: 134,
    distance: '1.0 km',
    distanceValue: 1.0,
    estimatedTime: '15 min',
    price: 60,
    isAvailable: true,
    experience: '6 years',
    qualifications: 'BSN, RN, Wound Care Cert.',
    bio: 'Certified wound care specialist. Expert in surgical wound dressing, diabetic ulcer management, catheter insertion and care at home.',
    reviews: [
      { name: 'Asif M.', rating: 5, comment: 'Very careful and gentle with dressing changes. Excellent hygiene practices.', date: '2 days ago' },
      { name: 'Nadia K.', rating: 5, comment: 'Handled my father\'s catheter change professionally. Very reassuring.', date: '1 week ago' },
      { name: 'Zara S.', rating: 4, comment: 'Good service for post-surgery wound care.', date: '2 weeks ago' },
    ],
    latitude: 24.8625,
    longitude: 67.0040,
  },
  {
    id: 'p9',
    name: 'Dr. Saima Naz',
    role: 'Doctor',
    specialization: 'Palliative Care',
    icon: 'hands-helping',
    color: '#A855F7',
    bgColor: '#F3E8FF',
    rating: 4.9,
    reviewCount: 62,
    distance: '2.5 km',
    distanceValue: 2.5,
    estimatedTime: '30 min',
    price: 200,
    isAvailable: true,
    experience: '12 years',
    qualifications: 'MBBS, Diploma Palliative Medicine',
    bio: 'Compassionate palliative care doctor specializing in pain management, symptom relief, and emotional support for patients with serious illnesses and their families.',
    reviews: [
      { name: 'Hamid R.', rating: 5, comment: 'Dr. Saima was a blessing for our family. She provided incredible comfort to my mother.', date: '3 days ago' },
      { name: 'Bushra T.', rating: 5, comment: 'Very empathetic and thorough. Made a difficult time much more bearable.', date: '1 week ago' },
    ],
    latitude: 24.8590,
    longitude: 67.0100,
  },
];
