export const SERVICES = [
  {
    id: '1',
    name: 'Home Doctor Visit',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    description:
      'Get a qualified doctor to visit your home for consultation, examination, and treatment.',
    features: [
      'General checkup & consultation',
      'Prescription & medication advice',
      'Follow-up visits',
      'Chronic disease management',
      'Referral to specialists',
    ],
    startingPrice: 150,
    duration: '30-60 min',
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: '2a',
    name: 'IM Injection',
    icon: 'needle',
    iconFamily: 'FontAwesome5',
    color: '#F97316',
    bgColor: '#FFF7ED',
    description:
      'Intramuscular injection services at home by trained nurses for fast medication delivery.',
    features: [
      'Intramuscular injections',
      'Antibiotic IM injections',
      'Pain relief injections',
      'Vitamin B12 injections',
      'Hormone injections',
    ],
    startingPrice: 300,
    duration: '10-20 min',
    rating: 4.8,
    reviewCount: 210,
  },
  {
    id: '2',
    name: 'IV Injection',
    icon: 'syringe',
    iconFamily: 'FontAwesome5',
    color: '#00C48C',
    bgColor: '#E6FAF3',
    description:
      'Professional IV injection services at your doorstep by certified nurses.',
    features: [
      'Intramuscular injections',
      'Subcutaneous injections',
      'Medication injections',
      'Antibiotic injections',
      'Pain relief injections',
    ],
    startingPrice: 400,
    duration: '15-30 min',
    rating: 4.9,
    reviewCount: 189,
  },
  {
    id: '2b',
    name: 'IV Line',
    icon: 'prescription-bottle',
    iconFamily: 'FontAwesome5',
    color: '#06B6D4',
    bgColor: '#CFFAFE',
    description:
      'IV line insertion and management at home by experienced nurses for medication delivery.',
    features: [
      'IV cannula insertion',
      'IV line setup & securing',
      'Medication through IV line',
      'Saline administration',
      'IV line removal & care',
    ],
    startingPrice: 500,
    duration: '30-60 min',
    rating: 4.8,
    reviewCount: 145,
  },
  {
    id: '2c',
    name: 'IV Drips',
    icon: 'tint',
    iconFamily: 'FontAwesome5',
    color: '#059669',
    bgColor: '#D1FAE5',
    description:
      'IV drip therapy at home including hydration, vitamin drips, and medication infusions.',
    features: [
      'Hydration drips',
      'Vitamin & nutrient drips',
      'Antibiotic drip therapy',
      'Blood transfusion support',
      'Post-surgery IV drip care',
    ],
    startingPrice: 700,
    duration: '45-120 min',
    rating: 4.9,
    reviewCount: 167,
  },
  {
    id: '3',
    name: 'Lab Tests',
    icon: 'flask',
    iconFamily: 'FontAwesome5',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description:
      'Home sample collection for blood tests, urine analysis, and other laboratory diagnostics.',
    features: [
      'Blood tests (CBC, sugar, lipid)',
      'Urine analysis',
      'Thyroid function tests',
      'Liver & kidney function tests',
      'COVID-19 & infectious disease tests',
    ],
    startingPrice: 30,
    duration: '15-30 min',
    rating: 4.7,
    reviewCount: 312,
  },
  {
    id: '4',
    name: 'X-Ray at Home',
    icon: 'x-ray',
    iconFamily: 'FontAwesome5',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    description:
      'Portable X-ray services brought to your home with digital results delivered quickly.',
    features: [
      'Chest X-ray',
      'Bone & joint X-ray',
      'Abdominal X-ray',
      'Dental X-ray',
      'Digital reports within 24 hours',
    ],
    startingPrice: 120,
    duration: '20-40 min',
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: '5',
    name: 'Nursing Care',
    icon: 'user-nurse',
    iconFamily: 'FontAwesome5',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description:
      'Professional nursing care at home for post-surgery recovery, elderly care, and more.',
    features: [
      'Post-surgery wound care',
      'Catheter & tube management',
      'Elderly patient care',
      'Vital signs monitoring',
      'Medication administration',
    ],
    startingPrice: 100,
    duration: '1-8 hours',
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: '6',
    name: 'Physiotherapy',
    icon: 'running',
    iconFamily: 'FontAwesome5',
    color: '#14B8A6',
    bgColor: '#CCFBF1',
    description:
      'Licensed physiotherapists provide rehabilitation and pain management at your home.',
    features: [
      'Post-surgery rehabilitation',
      'Back & neck pain therapy',
      'Sports injury recovery',
      'Stroke rehabilitation',
      'Joint mobility exercises',
    ],
    startingPrice: 90,
    duration: '45-60 min',
    rating: 4.7,
    reviewCount: 143,
  },
  {
    id: '7',
    name: 'Wound Dressing',
    icon: 'band-aid',
    iconFamily: 'FontAwesome5',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    description:
      'Professional wound care and dressing services at your home by trained nurses.',
    features: [
      'Surgical wound dressing',
      'Burn wound care',
      'Diabetic wound management',
      'Pressure sore treatment',
      'Sterile technique & infection prevention',
    ],
    startingPrice: 400,
    duration: '20-45 min',
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: '8',
    name: 'Catheterization',
    icon: 'procedures',
    iconFamily: 'FontAwesome5',
    color: '#0EA5E9',
    bgColor: '#E0F2FE',
    description:
      'Safe urinary catheter insertion, removal, and management at home by certified nurses.',
    features: [
      'Foley catheter insertion',
      'Catheter removal',
      'Catheter replacement',
      'Catheter care & hygiene',
      'Urine bag management',
    ],
    startingPrice: 2000,
    duration: '20-40 min',
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: '9',
    name: 'Palliative Care',
    icon: 'hands-helping',
    iconFamily: 'FontAwesome5',
    color: '#A855F7',
    bgColor: '#F3E8FF',
    description:
      'Compassionate palliative care at home for patients with serious illnesses, focusing on comfort and quality of life.',
    features: [
      'Pain management',
      'Symptom relief (nausea, breathlessness)',
      'Emotional & psychological support',
      'Family counseling & guidance',
      'End-of-life comfort care',
    ],
    startingPrice: 200,
    duration: '1-4 hours',
    rating: 4.9,
    reviewCount: 74,
  },
  {
    id: '10',
    name: 'Plaster of Paris',
    icon: 'bone',
    iconFamily: 'FontAwesome5',
    color: '#78716C',
    bgColor: '#F5F5F4',
    description:
      'Professional plaster of paris (POP) casting services at home for fractures and orthopedic support. Price varies by body area. POP with medicine package available for Rs 5,000 - 7,000.',
    features: [
      'Arm & wrist POP casting',
      'Leg & ankle POP casting',
      'Finger & toe splinting',
      'POP removal & replacement',
      'Post-fracture care & advice',
      'POP with medicine package (Rs 5,000 - 7,000)',
    ],
    startingPrice: 2000,
    pricingTiers: [
      { name: 'POP Cast Only', price: 2000, description: 'Basic POP casting by body area' },
      { name: 'POP + Medicine (Standard)', price: 5000, description: 'POP cast with standard pain relief & anti-inflammatory medicine' },
      { name: 'POP + Medicine (Premium)', price: 7000, description: 'POP cast with premium medicine, follow-up visit & post-care kit' },
    ],
    duration: '30-90 min',
    rating: 4.7,
    reviewCount: 63,
  },
];

export const PROVIDER_ROLES = [
  {
    id: 'doctor',
    name: 'Doctor',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    description: 'Licensed medical doctor for home visits and consultations',
  },
  {
    id: 'nurse',
    name: 'Nurse',
    icon: 'user-nurse',
    iconFamily: 'FontAwesome5',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Registered nurse for IV therapy, wound care, and patient care',
  },
  {
    id: 'lab_technician',
    name: 'Lab Technician',
    icon: 'flask',
    iconFamily: 'FontAwesome5',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'Certified lab technician for sample collection and testing',
  },
  {
    id: 'xray_technician',
    name: 'X-Ray Technician',
    icon: 'x-ray',
    iconFamily: 'FontAwesome5',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    description: 'Qualified radiographer for portable X-ray services',
  },
  {
    id: 'physiotherapist',
    name: 'Physiotherapist',
    icon: 'running',
    iconFamily: 'FontAwesome5',
    color: '#14B8A6',
    bgColor: '#CCFBF1',
    description: 'Licensed physiotherapist for rehabilitation and therapy',
  },
  {
    id: 'wound_specialist',
    name: 'Wound Care Specialist',
    icon: 'band-aid',
    iconFamily: 'FontAwesome5',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    description: 'Certified wound care nurse for dressings and catheterization',
  },
  {
    id: 'palliative_care',
    name: 'Palliative Care Specialist',
    icon: 'hands-helping',
    iconFamily: 'FontAwesome5',
    color: '#A855F7',
    bgColor: '#F3E8FF',
    description: 'Trained palliative care provider for comfort and end-of-life care',
  },
  {
    id: 'ortho_technician',
    name: 'Ortho Technician',
    icon: 'bone',
    iconFamily: 'FontAwesome5',
    color: '#78716C',
    bgColor: '#F5F5F4',
    description: 'Certified orthopedic technician for POP casting and fracture support',
  },
];

export const PROVIDER_BOOKINGS_DATA = [
  {
    id: 'pb1',
    serviceName: 'Home Doctor Visit',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    patientName: 'Ali Hassan',
    date: '2026-05-06',
    time: '10:00 AM',
    status: 'confirmed',
    price: 150,
    address: '45 Garden Road, Block C',
    notes: 'Patient has high blood pressure, regular checkup needed.',
  },
  {
    id: 'pb2',
    serviceName: 'Home Doctor Visit',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    patientName: 'Fatima Noor',
    date: '2026-05-06',
    time: '2:00 PM',
    status: 'pending',
    price: 150,
    address: '12 Clifton Ave, Apt 3A',
    notes: 'Fever and cough for 3 days.',
  },
  {
    id: 'pb3',
    serviceName: 'Home Doctor Visit',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    patientName: 'Usman Tariq',
    date: '2026-05-04',
    time: '11:00 AM',
    status: 'completed',
    price: 150,
    address: '78 Model Town, House 5',
    notes: 'Post-surgery follow-up.',
  },
];

export const BOOKINGS_DATA = [
  {
    id: 'b1',
    serviceId: '1',
    serviceName: 'Home Doctor Visit',
    icon: 'stethoscope',
    iconFamily: 'FontAwesome5',
    color: '#0D6EFD',
    bgColor: '#E7F1FF',
    date: '2026-05-06',
    time: '10:00 AM',
    status: 'confirmed',
    providerName: 'Dr. Ahmed Khan',
    price: 150,
    address: '123 Main Street, Apt 4B',
  },
  {
    id: 'b2',
    serviceId: '3',
    serviceName: 'Lab Tests',
    icon: 'flask',
    iconFamily: 'FontAwesome5',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    date: '2026-05-08',
    time: '8:00 AM',
    status: 'pending',
    providerName: 'HealthLab Services',
    price: 45,
    address: '123 Main Street, Apt 4B',
  },
  {
    id: 'b3',
    serviceId: '2',
    serviceName: 'IV Injection',
    icon: 'syringe',
    iconFamily: 'FontAwesome5',
    color: '#00C48C',
    bgColor: '#E6FAF3',
    date: '2026-04-28',
    time: '2:00 PM',
    status: 'completed',
    providerName: 'Nurse Sarah Ali',
    price: 400,
    address: '123 Main Street, Apt 4B',
  },
];
